---
name: module3_task3

'on':
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-artifact:
    runs-on: ubuntu-22.04

    steps:
      - name: clone repository
        uses: actions/checkout@v3

      - name: Install markdownlint
        run: npm install -g markdownlint-cli

      - name: Install markdownlint-check
        run: npm install -g markdown-link-check

      - name: run lint
        run: |
          cd ./module3_task3
          make lint

      - name: unit-tests
        run: |
          cd ./module3_task3
          make unit-tests

      - name: integration-tests
        run: |
          cd ./module3_task3
          make integration-tests

      - name: validate tests
        run: |
          cd ./module3_task3
          make validate

      - name: Install Hugo
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.87.0/\
          hugo_extended_0.87.0_Linux-64bit.deb
          sudo dpkg -i hugo_extended_0.87.0_Linux-64bit.deb

      - name: Setup environment
        run: |
          cd ./module3_task3
          ./setup.sh

      - name: Build
        run: |
          cd ./module3_task3
          make build

      - name: run package
        run: |
          cd ./module3_task3
          make package

      - name: Archive the package
        uses: actions/upload-artifact@v3
        with:
          name: awesome website
          path: ./module3_task3/awesome-website.zip

  build-release:
    permissions:
      contents: write
    needs: build-artifact
    if: startsWith(github.ref, 'ref/tags/1.0.0')
    runs-on: ubuntu-22.04
    steps:
      - name: clone repository
        uses: actions/checkout@v3

      - name: Download awesome-website.zip file
        uses: actions/download-artifact@v3
        with:
          name: awesome-website

      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          files: awesome-website.zip
          body_path: ./module3_task3/DEPLOY.md
