---
name: module3_task1

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: clone repository
        uses: actions/checkout@v3

      - name: Change to module3_task1 directory
        run: cd module3_task1

      - name: Run setup script
        run: ./setup.sh

      - name: Run Makefile execution
        run: |
          make help
          make build
          make run
          make stop
          make clean
        working-directory: module3_task1
