---
name: module3_task4

'on':
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    types: [opened, reopened, edited, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: clone repository
        uses: actions/checkout@v3

      - name: Install markdownlint
        run: npm install -g markdownlint-cli

      - name: Install markdownlint-check
        run: npm install -g markdown-link-check

      - name: run lint
        run: |
          cd ./module3_task4
          make lint

      - name: unit-tests
        run: |
          cd ./module3_task4
          make unit-tests

      - name: integration-tests
        run: |
          cd ./module3_task4
          make integration-tests

      - name: validate tests
        run: |
          cd ./module3_task4
          make validate

      - name: Install Hugo
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.87.0/\
          hugo_extended_0.87.0_Linux-64bit.deb
          sudo dpkg -i hugo_extended_0.87.0_Linux-64bit.deb

      - name: Setup environment
        run: |
          cd module3_task4
          ./setup.sh

      - name: Build
        run: |
          cd module3_task4
          make build

      - name: run package
        run: |
          cd ./module3_task4
          make package
          make clean

      - name: "archive build"
        uses: actions/upload-artifact@v3
        with:
          name: "upload package"
          path: module3_task4/awesome-website.zip

      - name: Release
        env:
          TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/1.0.1')
        with:
          files: |
            module3_task4/awesome-website.zip
            module3_task4/DEPLOY.md
          body: |
            ## Preparing a Release
            ## Deploying a Release
            ## release
            ## Pull Requests

      - run: gh release create v1.0.1 --title "v1.0.1"
            --notes DEPLOY.md 2>/dev/null || echo "OK"
