---
name: module3_task1

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: clone repository
        uses: actions/checkout@v3
      
      - name: Install markdownlint
        run: npm install -g markdownlint-cli

      - name: Change to module3_task1 directory
        run: cd module3_task1

      - name: Run setup script
        run: ./setup.sh

      - name: Run Makefile build
        run: |
          cd module3_task1
          make build
