---
name: module3_task3

'on':
  push:
    branches:
      - main
    tags:
      - '*'
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-22.04

    steps:
      - name: clone repository
        uses: actions/checkout@v3

      - name: Install markdownlint
        run: npm install -g markdownlint-cli

      - name: Install markdownlint-check
        run: npm install -g markdown-link-check

      - name: run lint
        run: |
          cd ./module3_task3
          make lint

      - name: unit-tests
        run: |
          cd ./module3_task3
          make unit-tests

      - name: integration-tests
        run: |
          cd ./module3_task3
          make integration-tests

      - name: validate tests
        run: |
          cd ./module3_task3
          make validate

      - name: Install Hugo
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.87.0/\
          hugo_extended_0.87.0_Linux-64bit.deb
          sudo dpkg -i hugo_extended_0.87.0_Linux-64bit.deb

      - name: Setup environment
        run: |
          cd module3_task3
          ./setup.sh

      - name: Build
        run: |
          cd module3_task3
          make build

      - name: run package
        run: |
          cd ./module3_task3
          make package
          make clean

      - name: Upload DEPLOY.md
        uses: actions/upload-artifact@v3
        with:
          name: DEPLOY.md
          path: module3_task3/DEPLOY.md

      - name: Download DEPLOY.md
        uses: actions/download-artifact@v3
        with:
          name: DEPLOY.md

      - name: Release
        env:
          TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 1.0.0
          release_name: 1.0.0
          files: |
            module3_task3/awesome-website.zip
          body_file: DEPLOY.md

      - name: "archive build"
        uses: actions/upload-artifact@v3
        with:
          name: "upload package"
          path: module3_task3/awesome-website.zip
