---
name: module3_task1

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: clone repository
        uses: actions/checkout@v3

      - name: setup
        run: |
          cd module3_task1
          ./setup.sh

      - name: Makefile Validation
        run: |
          cd module3_task1
          make build
