---
name: module3_task2

'on':
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: clone repository
        uses: actions/checkout@v3

      - name: Install markdownlint
        run: npm install -g markdownlint-cli

      - name: Install markdownlint-check
        run: npm install -g markdown-link-check

      - name: run lint
        run: |
          cd ./module3_task2
          make lint

      - name: tests
        run: make test

      - name: Install Hugo
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.87.0/\
          hugo_extended_0.87.0_Linux-64bit.deb
          sudo dpkg -i hugo_extended_0.87.0_Linux-64bit.deb

      - name: Setup environment
        run: |
          cd ./module3_task2
          ./setup.sh

      - name: Build
        run: |
          cd ./module3_task2
          make build

      - name: run package
        run: |
          cd ./module3_task2
          make package

      - name: Archive the package
        uses: actions/upload-artifact@v3
        with:
          name: awesome website
          path: ./module3_task2/awesome-website.zip
